# Generated by Django 4.2.16 on 2026-06-02 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Compte utilisateur lié (si le client a un accès)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiche_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
